config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'subscriptions/destroy'

  get 'customers/show'

  get 'pages/home'

  devise_for :users
  resources :classifieds
  get '/search', to: 'classifieds#search'
  
  # root 'classifieds#search'
  root 'pages#home'

  get 'stations/show'

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/legal', to: 'pages#legal'
  get '/pricing', to: 'pages#pricing'

  get '/dashboard', to:'users#dashboard'

  get '/users', to: 'pages#home'

  resources :subscriptions, only: [:destroy]

  # authenticate :user, lambda { |bu| bu.super_admin? } do
     mount Sidekiq::Web => '/sidekiq'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average.rb
class Average < ApplicationRecord
  belongs_to :resort
end

app/models/classified.rb
class Classified < ApplicationRecord
  belongs_to :resort
end

app/models/resort.rb
class Resort < ApplicationRecord
  has_many :classifieds
  
  has_many :subscriptions
  has_many :users, :through => :subscriptions

  has_many :averages
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :resort
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :subscriptions
  has_many :resorts, :through => :subscriptions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  def super_admin?
    email == "example@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# protect_from_forgery with: :exception
	before_action :set_locale
	#before_action :authenticate_user!

	private

	def set_locale
	I18n.locale = params[:locale] || I18n.default_locale
	end
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  attr_accessor :current_ville


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @classifieds = Classified.all
  end

  def about
  end

  def contact
  end

  def legal
  end

  def pricing
  end


end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
 
  def destroy
    Subscription.find(params[:id]).destroy
    redirect_to '/dashboard'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  # skip_before_action :verify_authenticity_token
  attr_accessor :current_ville_id

  def dashboard
    @resorts = Resort.all

    #Inscription
    s = Subscription.new
    s.user = current_user
    if params["ville"]
      s.resort = Resort.find_by_ville(params["ville"].downcase)
    end
    if s.resort
      @current_ville_id = s.resort.id
    end

    if Subscription.where(user_id:current_user.id).where(resort_id:@current_ville_id) == []
      s.save
    else
      flash.now[:alert] = "Vous êtes déjà abonné(e) à cette station!"  
    end

    @classifieds_hash = {}
    @subscriptions = Subscription.where(user_id:current_user.id)
    @subscriptions.each do |s|
      @classifieds_hash[Resort.find(s.resort_id).ville] = Classified.where(resort_id:s.resort_id)
    end
    
    #Do nos calculate average anymore, just load it from Average model :)
    @averages = Average.all
    @number_of_guests = params[:number_of_guests]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def list_station
    #take all ville in an array
    villes = Classified.group("ville").order("ville").pluck("ville")
    #iterate over the array
    list_of_station = []
    regions = ['66612889','66612807','66612786','66612960','66612917','66612918','66612972','66612919','66612803','66612962'] #Les trois vallées + Tignes et Val d'Isère

    villes.each do |i|
      if i
        if Resort.find_by_ville(I18n.transliterate(i))
           if Classified.where("ville":"#{i}").count > 10 && (regions.include? Resort.find_by_ville(I18n.transliterate(i)).region_number)
             list_of_station.push(titleize(i))
          end
        end
      end
    end

    return(list_of_station)

  end

  def titleize(title)
    new_title = ""

    title.split.each do |word|
      if new_title == ""
        new_title << word.capitalize
      elsif ["les", "le", "de"].include? word
        new_title << " "
        new_title << word
      elsif ["d'isere"].include? word
        new_title << " "
        new_title << "d'Isere"
      else  
        new_title << " "
        new_title << word.capitalize
      end
    end

    return new_title
  end


end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/classifieds/_demo.html.erb
<div class="container">
	<h1>Pourquoi Algoski ?</h1>
	<p>Vous êtes propriétaire d'un logement sur le domaine des Trois Vallées et souhaitez le louer ? Vous ne connaissez pas les tarifs pratiqués dans votre station ? 
	Algoski s'appuie sur une base de données de plusieurs milliers d'annonces pour vous aider à fixer vos prix.</p>
	<h1>Comment ça fonctionne ?</h1>
	<p>Renseignez votre station, puis indiquez le nombre de couchages de votre appartement. Notre algorithme va rechercher toutes les annonces correspondant à vos critères dans notre base de données, et calculer le prix moyen pour chaque semaine de la saison.</p>
	<h1>Que faire des résultats ?</h1>
	<p>Algoski vous permet de comparer vos tarifs à la moyenne pratiquée dans votre station pour un logement similaire au vôtre en terme de capacité d'accueil. Le calendrier des prix est également très utile pour évaluer les variations de prix d'une semaine à l'autre, et ajuster vos tarifs en conséquence. Enfin, le tableau de bord vous permet d'accéder en un clic à toutes les annonces de vos concurrents.</p>
	<h1>Quelques témoignages de nos clients</h1>
	<p>Etienne, 34 ans, propriétaire d'un T2 à Brides-les-Bains : "Algoski a changé ma vie en profondeur. Je suis désormais un homme comblé."</p>
	<h1>Ils parlent de nous</h1>
	<p>Personne. Tristesse.</p>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	
	<!-- <div class="navbar navbar-inverse"> -->
    	<div class="container">
    		
    		<div class="footer-content">

    			<ul>
	        <!-- <ul class="nav navbar-nav"> -->
						<!-- <li><a href="/pricing">Tarifs</a></li>
						<li><a href="/legal">Mentions légales</a></li> -->
						<li><a href="/contact">Contact</a></li>
					</ul>
				
					<!-- <ul class="nav navbar-nav navbar-right"> -->
					<ul class="disappear-small">
						<li>Projet réalisé dans le cadre de <a href="http://www.thehackingproject.org/" target="_blank">The_Hacking_Project</a></li>
					</ul>
		  	
		  	</div>

			</div>
	<!-- </div> -->

</footer>

app/views/layouts/_header.html.erb
<header>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container" >

      <!-- logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-logo" href="/">
                <%= image_tag('logo-grey.png', size:'30', class:'brightness')%>
            </a>
            <a class="navbar-brand" href="/">
                Algoski
            </a>
        </div>

    <!-- Menu items -->
      <div class="collapse navbar-collapse" id="mainNavBar">
        <ul class="nav navbar-nav navbar-right dropdown-toggle">
            <% if user_signed_in? %>
                <li><%= link_to "Mon tableau de bord", dashboard_path, class:"dropdown-toggle" %></li>
                <li><%= link_to "#{current_user.email}", edit_user_registration_path %></li>
                <li><%= link_to "Déconnexion",destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to "Se connecter", new_user_session_path %></li>
            <% end %>
        </ul>
      </div>
           
      </div> 
    </div>
    
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Algoski - Le comparateur des locations au ski</title>
  
	    <meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>

	    <%= favicon_link_tag 'logo.png' %>
	    
	</head>

	<body>
		<%= render 'layouts/header' %>

		
			<% if notice %>
			<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
			<p class="alert alert-danger"><%= alert %></p>
			<% end %>

			<%= yield %>
			<%= render 'layouts/footer' %>
		
		
		
		<%= render 'cookies_eu/consent_banner' %>
  	
	</body>

</html>

app/views/pages/about.html.erb
<h1>About Us</h1>

app/views/pages/contact.html.erb
<div class="container-fluid" >
    <div class="row">
		<div class="form col-md-offset-2 col-md-8">
			<div class="form-head">
			</div> 
			<div class="form-body">
				<div class="row">
					<div class="form-body-title col-md-offset-1 col-md-10 text-center">
						<h1>L'équipe derrière Algoski</h1>
						<br>
						<h4>
							<ul class="contact-info">
								<li>
									Isabelle Bonnet
									<a href="mailto:isabellecorp@gmail.com">
										<i class="fa fa-envelope" aria-hidden="true"></i>
									</a>
									<a href="https://github.com/isarceaux" target="_blank">
										<i class="fa fa-github" aria-hidden="true"></i>
									</a>
									<a href="https://www.linkedin.com/in/bonnetisabelle/" target="_blank">
										<i class="fa fa-linkedin" aria-hidden="true"></i>
									</a>
								</li>
								<br>
								<li>
									Marina Kirszenberg
									<a href="mailto:mk_pro@outlook.fr">
										<i class="fa fa-envelope" aria-hidden="true"></i>
									</a>
									<a href="https://github.com/marinakiri" target="_blank">
										<i class="fa fa-github" aria-hidden="true"></i>
									</a>
									<a href="https://www.linkedin.com/in/marinakir/" target="_blank">
										<i class="fa fa-linkedin" aria-hidden="true"></i>
									</a>
								</li>
								<br>
								<li>
									Hong Luu
									<a href="mailto:luu.bichhong@gmail.com">
										<i class="fa fa-envelope" aria-hidden="true"></i>
									</a>
									<a href="https://github.com/orangespa" target="_blank">
										<i class="fa fa-github" aria-hidden="true"></i>
									</a>
									<a href="https://www.linkedin.com/in/luu-bich-hong-7b7ab638/" target="_blank">
										<i class="fa fa-linkedin" aria-hidden="true"></i>
									</a>
								</li>
								<br>
							</ul>
						</h4>
						<br>
						<hr>
							<h4>Un grand merci à nos mentors pour leur aide précieuse &hearts;</h4>
							<br>
							<p>
								<ul class="contact-info">
									<li>Vincent Algayres
										<a href="https://www.linkedin.com/in/vincent-algayres-10925567/" target="_blank">
											<i class="fa fa-linkedin" aria-hidden="true"></i>
										</a>
									</li>
									<br>
									<li>Jean-Baptiste Barth
										<a href="https://www.linkedin.com/in/jean-baptiste-barth-9b407940/" target="_blank">
											<i class="fa fa-linkedin" aria-hidden="true"></i>
										</a>
									</li>
									<br>
									<li>Alexandre Kirszenberg
										<a href="https://www.linkedin.com/in/alexandre-kirszenberg-b45733b6/" target="_blank">
											<i class="fa fa-linkedin" aria-hidden="true"></i>
										</a>
									</li> 
								</ul>
							</p>
					</div>
					<div class="form-body-info col-md-offset-1 col-md-10">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="slideshow"> 
      <div class="col-xs-offset-1 col-xs-10">
        <h1 class="slideshow-h1">Vous louez un bien à la montagne ?</h1>
        <h2 class="slideshow-h2">Visualisez les prix de tous vos concurrents sur la saison</h2>
      </div>
        
        <div class="row">
          
          <%= form_tag({controller: "users", action: "dashboard"}, method: :get, class:"form-inline" ) do %>
            <div class="input-group col-md-offset-4 col-md-4 col-xs-offset-1 col-xs-10">
                <%= select_tag(:ville_searched, options_for_select(list_station), multiple: false, class:'form-control select-resort') %>
                <span class="input-group-btn">
                  <%= submit_tag 'Go !', class: "btn btn-primary" %>
                </span>
              <% end %>          
          </div>
          
        </div>

    </div>
  </div>

<div class="row">
  <div class="col-md-offset-2 col-md-2 search-results homepage col-xs-offset-1 col-xs-10">
    <div class="col-md-offset-1 col-md-10">
      <h2>Mise en location</h2>
      <p><i class="fa fa-question icon-big" aria-hidden="true"></i></p>
      <p>Quel prix dois-je fixer pour louer mon appartement ?</p>
    </div>
  </div>
  <div class="col-md-offset-1 col-md-2 search-results homepage col-xs-offset-1 col-xs-10">
    <div class="col-md-offset-1 col-md-10">
      <h2>Pendant la saison</h2>
      <p><i class="fa fa-calendar-plus-o icon-big" aria-hidden="true"></i></p>
      <p>Je n'ai pas encore loué, suis-je trop cher ? Est-ce normal ?</p>
    </div>
  </div>
  <div class="col-md-offset-1 col-md-2 search-results homepage col-xs-offset-1 col-xs-10">
    <div class="col-md-offset-1 col-md-10">
      <h2>Après la location</h2>
      <p><i class="fa fa-star icon-big" aria-hidden="true"></i></p>
      <p>Puis-je faire mieux l'année prochaine ? Comment ?</p>
    </div>
  </div>
</div>

  <div class="row">
      <div class="slideshow-smaller">
        <div class="col-xs-offset-1 col-xs-10 box-in-box">
          <h3><i class="fa fa-plus" aria-hidden="true"></i> Louer au meilleur prix</h3>
          <h3><i class="fa fa-plus" aria-hidden="true"></i> Louer plus souvent</h3>
        </div>
      </div> 
  </div>

  <div class="row">
    <div class="col-md-offset-3 col-md-6 search-results col-xs-offset-1 col-xs-10 homepage">
      <h2><%=@classifieds.count%> annonces</h2>
      <div class="col-md-offset-1 col-md-10 col-xs-offset-1 col-xs-10">
      <p>référencées dans notre base de données</p>
      <p>pour comparer vos prix avec la concurrence</p>
      <p>à disposition pour vous, gratuitement !</p>
      <a class="dynamic-btn" href="dashboard">
          Tester
          <i class="fa fa-check-circle" aria-hidden="true"></i>
      </a>
      </div>
    </div>
  </div>

</div>

app/views/pages/legal.html.erb
<h1>Legal Notice</h1>

app/views/pages/pricing.html.erb
<h1>Pricing</h1>

app/views/pages/results.html.erb
<p>
	Nous avons trouvé XX annonces correspondant à votre recherche.
	Station : XX
	Nombre de convives : XX
</p>

<p>
	Pour accéder aux résultats, <%= link_to "connectez-vous", new_user_session_path, :class => 'navbar-link'  %>.
<br>
  Pas encore inscrit ? <%= link_to "Inscrivez-vous ici", new_user_registration_path, :class => 'navbar-link'  %>.
</p>

app/views/users/dashboard.html.erb
<div class="container-fluid" id="list-of-resorts">
<div class="row">
  <div class="search-results col-md-offset-2 col-md-8 margin-top-extra">
  <br>
  <h1><b>Bienvenue sur votre tableau de bord !</b></h1>
  <br>

  <% if @subscriptions == nil || @subscriptions.count == 0 %>
    <div class="row not-subscribed"><p>Ajoutez une station avec le champ de recherche ci-dessous.</p></div>
  <% end %>

  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <% @subscriptions.each do |s| %>
        <div class="col-md-3">        
            <div class="station-bloc">
              <div class='col-md-offset-10'>
                <%= link_to "/subscriptions/#{s.id}", method: :delete do %>
                  <i class='fa fa-times'></i>
                <% end %>
              </div>
                <%= link_to dashboard_path(anchor: s.resort.ville) do %>
                  <h2> <%= titleize(s.resort.ville)%> </h2>
                <% end %>

              <div>
                <%= @classifieds_hash[Resort.find(s.resort_id).ville].count %> annonces
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <hr>
    </div>
  </div> 

  <div class="row">
    <h1>Ajouter une nouvelle station :</h1>
    
      <%=form_tag({controller: 'users', action: 'dashboard'}, method: :get, class:"form-inline") do %>
      <div class="input-group col-md-offset-4 col-md-4 col-xs-offset-1 col-xs-10">
        <%= select_tag(:ville, options_for_select(list_station), multiple: false, class:'select-resort form-control') %>
        <span class="input-group-btn">
          <%= submit_tag "OK", class: "btn btn-primary" %>
        </span>
      <% end %>
      </div>
    
  </div>

</div>
</div>



  <!-- Initialization for calendar -->
  <% month_list = ["décembre", "janvier", "février", "mars", "avril", "mai"] %>
  <% starting_date = Date.new(2017,12,9) %>
  <% frequency = 7 %>

  <!-- End of initialization for calendar -->

  <% unless @subscriptions.nil? || @subscriptions.size == 0 %>

  <% @subscriptions.each do |s| %>

    <% if @number_of_guests %>
      <% number_of_guests = @number_of_guests %>
    <% else %>
      <% number_of_guests = 4 %> <!-- Changer la façon d'initialiser pour le faire sur quelque chose qui existe -->
    <% end%>

<div class="row" id="<%=s.resort.ville_url%>">
    <div class="search-results-dashboard col-md-offset-2 col-md-8">
    <% selected_classifieds = @classifieds_hash[Resort.find(s.resort_id).ville] %>
      <div class="search-results-header">
        <h3><%= titleize(s.resort.ville) %></h3>
        <h4><%= selected_classifieds.count %> annonces</h4>
      </div>
  
  <!-- Afficher le nombre de guests dans un formulaire -->
   <!-- To be prompted for number_of_guests -->
      <% list_of_number_of_guests2 = selected_classifieds.group('number_of_guests').pluck('number_of_guests') %>
      <% list_of_number_of_guests2 = list_of_number_of_guests2.sort %>
      <!-- End of to be prompted for number_of_guests -->

      <div class="row">
        <div class="col-md-offset-1 col-md-10">
          
            <%= form_tag({controller: "users", action: "dashboard"}, method: :get, class:'form-inline form-nb-guests') do %>
              <%= label_tag(:number_of_guests, "Nombre de personnes dans l'appartement :") %>
            <div class="input-group">
              <%= select_tag(:number_of_guests, options_for_select(list_of_number_of_guests2), prompt:number_of_guests, class:'form-control select-resort')%>
              <span class="input-group-btn">
                <%= submit_tag 'OK', class: "btn btn-primary" %>
              </span>
            <% end %>
          </div>
        </div>
      </div>

  <!-- Fin de afficher le nombre de guests dans un formulaire -->

  <!-- Calendar -->
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <div>
        <% 6.times do |j| %>
          <div class="col-md-2 col-calendar col-xs-offset-1 col-xs-10">
            <div class="col-xs-12 calendar month">
              <%= month_list[j].capitalize %>
            </div>
            <% 4.times do |i| %>
            <div class="average-price-box col-xs-12 calendar">
              <% current_date = starting_date + (i+j*4)*7 %>
              <div class="date">
                <div class="mini-date start-date">
                  <p>Sa</p>
                  <p><span class="bold"><%= "#{current_date.mday}" %></span></p>
                </div>
                <div class="mini-date end-date">
                  <p>Sa</p>
                  <p><span class="bold"><%= "#{(current_date+7).mday}" %></span></p>
                </div>
              </div>
              <div class="price">
              <% if @averages.where(resort:s.resort).where(start_date:current_date).find_by_number_of_guests(number_of_guests) != nil %>  
                <%= (@averages.where(resort:s.resort).where(start_date:current_date).find_by_number_of_guests(number_of_guests).average_value*(frequency)).round %>
                 €
                <p><%= @averages.where(resort:s.resort).where(start_date:current_date).find_by_number_of_guests(number_of_guests).average_count %> annonces</p>
              <% else %>
                -
              <% end %>
            </div>
          </div>
          <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<!-- end of calendar -->

<!-- The table of data -->

<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <br>
    <hr>
    <h3>Liste des annonces</h3>
    <table class="classifieds-table table table-striped table-bordered" cellspacing="0" width="100%">
      <tfoot>
        <tr>
          <th>Semaine</th>
          <th><i class="fa fa-user" aria-hidden="true"></i></th>
          <!-- <th>Prix</th>
          <th>Nom de l'annonce</th> -->
          <!-- <th>Code annonce</th> -->
        </tr>
      </tfoot>  
      <thead>
        <tr>
          <th>Semaine</th>
          <th><i class="fa fa-user" aria-hidden="true"></i></th>
          <th>Prix</th>
          <th>Nom de l'annonce</th>
          <!-- <th>Code annonce</th> -->
        </tr>
      </thead>
      <tbody>
      <% selected_classifieds.each do |sc| %>
        <tr>
          <td><%= sc.start_date.mday%>/<%= sc.start_date.mon%>/<%=sc.start_date.year %></td>
          <td><%= sc.number_of_guests %></td>
          <td><%= (sc.price*7).round %>€</td>
          <td><a target="_blank" href="http://www.abritel.fr<%=sc.link%>"><%= sc.title %></a></td>
          <!-- <td><%= sc.abritel_classified_id%></td> -->
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- End of the table of data -->

</div>

<div class="col-md-offset-4 col-md-4">
  <a id="scroll-top" class="scroll-top dynamic-btn" href="#top">
    Revenir au tableau de bord
    <i class="fa fa-chevron-circle-up" aria-hidden=true></i>
  </a>    
</div>

</div>

  

  <%end%>

  <% end %>



    

</div>